---
title: "Risk Factor Analysis"
output: 
  html_document:
    keep_md: TRUE
    self_contained: true
required_packages:  ['github://HBGD-UCB/longbowRiskFactors','github://jeremyrcoyle/skimr@vector_types', 'github://tlverse/delayed']
params:
  roles:
    value:
      - exclude
      - strata
      - id
      - W
      - A
      - Y
  data: 
    value: 
      type: 'web'
      uri: 'https://raw.githubusercontent.com/HBGD-UCB/longbowRiskFactors/master/inst/sample_data/birthwt_data.rdata'
  nodes:
    value:
      strata: ['study_id', 'mrace']
      id: ['subjid']
      W: ['apgar1', 'apgar5', 'gagebrth', 'mage', 'meducyrs', 'sexn']
      A: ['parity_cat']
      Y: ['haz01']
  script_params:
    value:
      parallelize:
        input: checkbox
        value: FALSE
      count_A:
        input: checkbox
        value: TRUE
      count_Y:
        input: checkbox
        value: TRUE        
      baseline_level:
        input: 'character'
        value: "[1,2)"
  output_directory:
    value: ''
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = FALSE, message=FALSE, eval.after = 'fig.cap')
options(scipen=999)
```

```{r params, warning=FALSE, message=FALSE}
library(longbowtools)
library(longbowRiskFactors)
library(sl3)
library(tmle3)
library(data.table)
library(stringr)

params_object <- get("params")
print(params_object)

get_tl_data2 <- function (params_object = NULL){
    if (is.null(params_object)) {
        params_object <- get("params", envir = parent.frame())
    }
    uri <- params_object[[1]]$data$uri

    print(uri)
    #cat(uri,"\n")
    if (!(file.exists(uri) || grepl("^http(s)*://", uri))) {
        stop("File does not exist: ", uri)
    }
    extension <- str_to_lower(str_extract(uri, "\\.([^\\.]+)$"))
    if (extension == ".csv") {
        data <- fread(uri)
    }
    else if (extension == ".rds") {
        data <- readRDS(uri)
        setDT(data)
    }
    else if (extension == ".rdata") {
        vars <- load(file(uri, "rb"))
        dfs <- sapply(vars, function(var) is.data.frame(get(var)))
        if (length(which(dfs)) == 0) {
            stop("rdata file does not contain a data frame")
        }
        var <- vars[which(dfs)][1]
        data <- get(var)
        setDT(data)
    }
    else {
        stop("unrecognized data file extension: ", extension)
    }
    return(data)
}

 # data <- get_tl_data()
 # 
 # knitr::kable(head(data))

```
